services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_usuariosapp
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Coti@2025
    ports:
      - "1435:1433"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_usuariosapp
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_usuariosapp
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge